### ISSUE TITLE
Image Render

### ISSUE THREAD

**Issue by ghost** [RMuseLive/rmuselive#26]
Component for rendering an image. Needs props:
- Filestack URI
- Size (in rows/columns)
- Position (in rows/columns)

**Comment by deoism** [comment]
is react-image a good way to render this for you - not sure of image src ( local -database or remote url)
using simple local /images/ folder for now
I'll go with the most flexable

**Comment by deoism** [comment]
didn't filestack URI ( not clear what that is)
but did size and position random local images ( /public/images/xxxx.jpg)
more later - keep me informed pls
